name = "webupdatereminder-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "13a17e727e9ce2c37d5450a869ac1273"

[[kv_namespaces]]
binding = "SITES_KV"
id = "91b27c9159af4c17a2bef8c7c1f85a9d"

[triggers]
# Daily report 7:00 Spain + hourly uptime check
crons = ["0 6 * * *", "0 * * * *"]
